site_name: Avaliação do Cebraspe
site_description: Projeto da disciplina FGA315 - Avaliação da Qualidade de Software
theme:
  name: material
  language: pt
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
  palette:
    - scheme: default
      primary: blue
      accent: indigo
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Modo Noturno
nav:
  - Início: index.md
  - Fases:
      - "Fase 1 - Definição dos Requisitos": fase1.md
      - "Fase 2 - Definição das Métricas": fase2.md
      - "Fase 3 - Planejamento da Avaliação": fase3.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SEU-REPO
